# Site settings
author: Cristina Torres Martinez
title: The Times of a Newb
header-img: img/home-bg.png
email: c.torres.martinez.97@gmail.com
copyright_name: Cristina Torres Martinez
description: > # this means to ignore newlines until "baseurl:"
  A Memoir... But Not
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cristinatorresmartinez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
